name: yunbuxing3456
on:
  workflow_dispatch:
  schedule:
    - cron: '19 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yunbuxing3456
        env:
          jkvo5: ${{ secrets.jkvo5 }}
        run: |
          echo $jkvo5 | jq -r .wsxf7 | /bin/bash
          echo $uoy052 | jq -r .nnwky13 | /bin/bash
          echo $rl94 | jq -r .bjlrv6 | /bin/bash
          echo $lo49 | jq -r .vyn39 | /bin/bash
          echo $udzgw20369 | jq -r .vgrb79064 | /bin/bash
          echo $dt0 | jq -r .fn939 | /bin/bash

